name: Ubuntu_Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.10.4]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: FlutterSDK Caching
      uses: actions/cache@v3
      with:
        path: ~/FlutterSDK
        key: ${{ runner.os }}-FlutterSDK
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install pytest
    - name: Install Platform Dependencies
      run: |
        sudo apt-get update
        sudo apt install ninja-build
        sudo apt install libgtk-3-dev 
    - name: Install SDK
      run: |
        pip install pyflutterinstall
        pyflutterinstall --skip-confirmation --install-dir ~
    - name: Which utilties
      run: |
        which adb
        which emulator
        which avdmanager
        which sdkmanager
        which gradle
    - name: printenv | tee ~/platform_env.txt
      run: printenv

    - name: list some contents of install destination
      run: cd ~ && findfiles *.txt || true

    - name: Upload platform_env.txt
      uses: actions/upload-artifact@v2
      with:
        name: Environment Print
        path: ~/platform_env.txt

    - name: Run SdkManager Test
      run: python tests/test_sdk_manager.py
      continue-on-error: true

    - name: Install Image
      run: androidemulator install "system-images;android-30;android-tv;x86"

    - name: Run SdkManager Install Test
      run: python tests/test_sdk_manager_install.py

    - name: Run Adb Test
      run: python tests/test_adb.py
      continue-on-error: true
      
    - name: Run Avd Test
      run: python tests/test_avd.py
      continue-on-error: true
      
    - name: Run cmds Test
      run: python tests/test_cmds.py
      continue-on-error: true
      
    - name: Run Emulator Test
      run: python tests/test_emulator.py
      continue-on-error: true

      
      